### ISSUE TITLE
Can't import after pip install. Tested all in ubuntu and macos

### ISSUE THREAD

**Issue by leopku** [amoallim15/cuckoo_filter#3]
## OS
* Ubuntu 18.04.3 LTS
* Mac OS X 10.15.7

## ENV

* python 3.6.7
* pip 20.2.4

After `pip install cuckoo-filter`, only one dir named `cuckoo_filter-1.0.5.dist-info` in `site-packages`.

```shell
❯❯❯ ll | rg -i cuckoo                                       master
drwxrwxr-x    - leo 27 Oct 16:37 cuckoo_filter-1.0.5.dist-info
```

It same in Mac OS and Ubuntu.

When run `from cuckoo_filter import CuckooFilter`, "No module named 'cuckoo_filter'" occured.

**Comment by leopku** [comment]
By downloading the sources and running `python setup.py install`, this awesome module can be imported now.

It will be appreciate if broken of pip installation can be fixed.

**Comment by amoallim15** [comment]
Oops, I forgot to automate uploading the new build to pypi ^^!
You can make a pip installation from now, thanks for the catch :)

**Comment by leopku** [comment]
It works now.
Thanks.

**Comment by amoallim15** [comment]
my pleasure ^^
